name: Tests

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  run-backend-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Restore dependencies
        run: dotnet restore ./RBacServer/RBacServer.csproj

      - name: Build the project
        run: dotnet build ./RBacServer/RBacServer.csproj --configuration Release

      - name: Run tests
        run: dotnet test ./RBacServer/RBacServer.csproj --configuration Release --no-build
